### ISSUE TITLE
How to properly select an element to scroll to?

### ISSUE THREAD

**Issue by michael-ziedalski** [KoryNunn/scroll-into-view#69] opened 2019-07-03 06:48 UTC
Pardon if this is an incredibly amateur mistake, but whenever I call `scrollIntoView(some_element_name)`, it seems that nothing happens, so I must be doing something wrong. Am I simply calling the desired element incorrectly, or in the wrong context?

Any guidance on getting this to work would by greatly appreciated.

```js
const puppeteer = require("puppeteer");
var scrollIntoView = require('scroll-into-view');

// puppeteer usage as normal
puppeteer.launch({ headless: false }).then(async browser => {

  const page = await browser.newPage();

  const navigationPromise = page.waitForNavigation();

  await page.setViewport({ width: 1440, height: 794 });

  var data = [];

  await page.goto('https://www.glassdoor.com/Reviews/Microsoft-Reviews-E1651.htm');

  // Scrolling to a random aspect of a company review comes into view,
  // is not working.
  scrollIntoView("span.summary", {
    time: 1000
  });

})
```

**Comment by osi-oswald** [comment] 2019-07-03 10:49
I guess you are supposed to pass a HTMLElement. 

In your case passing `document.querySelector('span.summary')` instead of just the query string `'span.summary'`.

**Comment by michael-ziedalski** [comment] 2019-07-03 18:52
Ok, so I changed it to `scrollIntoView(document.querySelector('span.summary'))`, but then I get an error saying
`UnhandledPromiseRejectionWarning: ReferenceError: document is not defined`

Another approach I have taken is the following, where the script does not report any errors, but it just keeps running without scrolling anywhere:

const puppeteer = require("puppeteer");
const cheerio = require('cheerio');

var scrollIntoView = require('scroll-into-view');

// puppeteer usage as normal
puppeteer.launch({ headless: false }).then(async browser => {

  const page = await browser.newPage();

  const navigationPromise = page.waitForNavigation();

  await page.setViewport({ width: 1440, height: 794 });

  var data = [];

  await page.goto('https://www.glassdoor.com/Reviews/Microsoft-Reviews-E1651.htm');

  // Loading JQuery to be able to find the element?
  const html = await page.content();
  const $ = cheerio.load(html);

  // Scrolling to a random aspect of a company review comes into view,
  // is not working.
  scrollIntoView($('*').find('span.summary')[0], {
    time: 1000
  });

})

**Comment by KoryNunn** [comment] 2019-07-04 19:05
Hi @michael-ziedalski 

You are using puppeteer, which uses webdriver to remotely execute commands on a browser.

You are running scroll-into-view in node, and passing a virtual cheerio DOM node into it.

Because you aren't actually working with the browser directly, every action you take has to be asynchronous, and scroll-into-view is not designed to work in a case like this (remote control of a web browser via node)

You can easily solve this however, by first executing the standalone scroll-into-view code in the browser with `page.evaluate(script)`

You can then call it via the same function eg: `page.evaluate("scrollIntoView(document.querySelector('.foo'))")`

**Comment by KoryNunn** [comment] 2019-07-04 19:08
Btw an analogy would be: you are trying to beat eggs through a TV, you can see the eggs, and you are holding the whisk, but it won't work unless you can send your whisk to where the eggs are :)

**Comment by michael-ziedalski** [comment] 2019-07-04 20:44
KoryNunn, by executing the standalone scroll-into-view code, do you mean a separate file in the folder housing my script? And what would be in it then?

Pardon these elaborations, I am still rough with javascript around the edges ^^; .

**Comment by KoryNunn** [comment] 2019-07-04 22:41
The easiest way would be to read that file off disk with fs.readFile('./path/to/script.js', 'utf8') and pass the resulting string into evaluate()

**Comment by KoryNunn** [comment] 2019-07-04 23:40
And, the copy-past-able version, just remember to *download the scrollIntoView.min.js file* and *change the fs.readFileSync path*

```js
const puppeteer = require("puppeteer");
const cheerio = require('cheerio');

var scrollIntoView = require('scroll-into-view');

// puppeteer usage as normal
puppeteer.launch({ headless: false }).then(async browser => {

  const page = await browser.newPage();

  const navigationPromise = page.waitForNavigation();

  await page.setViewport({ width: 1440, height: 794 });

  var data = [];

  await page.goto('https://www.glassdoor.com/Reviews/Microsoft-Reviews-E1651.htm');

  // Loading JQuery to be able to find the element?
  const html = await page.content();

  const scrollIntoViewScript = fs.readFileSync('./path/to/scrollIntoView.min.js', 'utf8');
  
  page.evaluate(scrollIntoViewScript);

  page.evaluate(`
    scrollIntoView(document.querySelector('span.summary'))
  `);
})
```

**Comment by michael-ziedalski** [comment] 2019-07-04 23:43
So, I am trying to run this script,

**Comment by michael-ziedalski** [comment] 2019-07-05 00:39
(thank you for all the guided help, I do appreciate it greatly ^^; )

Running the above, I get a node error saying `UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: scrollIntoView is not defined`. I tried putting `const scrollIntoView = require('scroll-into-view');` in different places in the script, but it does not change anything, and I know I have it installed with `npm install scroll-into-view`.

**Comment by KoryNunn** [comment] 2019-07-05 00:56
You do not have to install scrollIntoView anywhere in your code, because you are not running it in node, but rather in the browser you are automating.

I'll edit my above, let me know if it works now.

**Comment by KoryNunn** [comment] 2019-07-05 01:19
Might be worth adding this to the launch call:

```js
"args":["--disable-features=CrossSiteDocumentBlockingAlways,CrossSiteDocumentBlockingIfIsolating"]
```

eg:

```js
const browser = await puppeteer.launch({
    headless: false,
    args: ["--disable-features=CrossSiteDocumentBlockingAlways,CrossSiteDocumentBlockingIfIsolating"]
});
```

**Comment by KoryNunn** [comment] 2019-07-09 05:54
@michael-ziedalski how did you go?

I'll close this since it's never really been about scroll-into-view.

Let me know if you have any more questions.

**Closed by KoryNunn** 2019-07-09 05:54 UTC

**Comment by michael-ziedalski** [comment] 2019-07-12 19:06
So, I put in all of your comments, and attempted to make the script work, but it ends up freezing, and throwing up a console error in the browser saying 

`"Refused to load the script [insert your url to the github code] because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'..."`

I imagine this is a puppeteer thing, so I am trying to resolve it myself.

**Comment by michael-ziedalski** [comment] 2019-07-15 06:12
I think I managed to bypass that error by using a Puppeteer specific command right before the url is opened, ` await page.setBypassCSP(true)`.

However, now I have a new error, which says

`Uncaught ReferenceError: scrollIntoView is not defined
    at HTMLScriptElement.`

Would you have any idea what might be causing that?

**Comment by KoryNunn** [comment] 2019-07-15 11:58
Either the script has not finished loading, or an error is occuring to prevent it from loading correctly, or it does not have access to the same global scope.

If you can make a simple reproduction, put it in a new repo, and link it here, I'll have a look.
